apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: alexpalko-com-tls
spec:
  secretName: alexpalko-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: alexpalko.com
  dnsNames:
    - alexpalko.com
    - www.alexpalko.com